### ISSUE TITLE
A question rather than an issue

### ISSUE THREAD

**Issue by krishnak** [petabite/uWeb#5]
How do you shutdown your server or generally a task that has been started using uasyncio.start_server

**Comment by petabite** [comment]
Hi,

If you start your task with [`uasyncio.create_task`](https://docs.micropython.org/en/latest/library/uasyncio.html#uasyncio.create_task), it will return a [`Task`](https://docs.micropython.org/en/latest/library/uasyncio.html#class-task) object. You can then use the `Task.cancel` method to cancel it.

**Comment by krishnak** [comment]
Thank you for replying, I have a code like this

```
Class mytask
def __init__():
   code here
async def mytaskhandle:
  code here

async def run(self):
        try:
            return await asyncio.start_server(self.mytaskhandle, self.address, self.port)
        except asyncio.core.CancelledError:
                    # Shutdown server
            print("Called here")
            return
```

from another class main

```
aync def main:
       server = asyncio.create_task(mytaskinstance.run())

asyncio.run(main())
       # server starts up here 

```
when you mean Task.cancel() - how do I capture the asyncio.core.CancelledError inside the task - it doesn't have a while loop like other async tasks, please use your webserver as a reference and provide me a code where the asyncio.core.CancelledError can be caught.

In other tasks,I have some form of while loop where there is a asyncio.sleep() - I can do a try: except: there but there is nothing available here

**Comment by krishnak** [comment]
This has been answered [here](https://github.com/orgs/micropython/discussions/9289#discussioncomment-3630636)
